name: "Format Code: ensure code formatting guidelines are met"
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  format-code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - uses: ministryofjustice/github-actions/code-formatter@63d84d475bc20877f741d768dd9c2d89af51170d # v18.2.0
        with:
            ignore-files: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
